[package]
name = "cuda_builder"
version = "0.3.0"
edition = "2021"
authors = ["Riccardo D'Ambrosio <rdambrosio016@gmail.com>", "The rust-gpu Authors"]
license = "MIT OR Apache-2.0"
description = "Builder for easily building rustc_codegen_nvvm crates"
repository = "https://github.com/Rust-GPU/rust-cuda"
readme = "../../README.md"

[package.metadata.docs.rs]
no-default-features = true

[features]
default = []
# HACK(see rust-gpu/spirv-builder): use `dep:` to avoid Cargo auto-creating a feature
# with the dependency name. Consumers must explicitly opt-in to compiling the backend.
rustc_codegen_nvvm = ["dep:rustc_codegen_nvvm"]

[dependencies]
rustc_codegen_nvvm = { version = "0.3", path = "../rustc_codegen_nvvm", optional = true }
nvvm = { path = "../nvvm", version = "0.1" }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
