[book]
authors = ["Riccardo D'Ambrosio<rdambrosio016@gmail.com>"]
language = "en"
src = "src"
title = "The Rust CUDA Guide"
description = "How to write GPU compute code with Rust using rustc_codegen_nvvm and CUDA"
